// Run with: npx tsx src/_gen_squidgame_thumbs.ts
// Generates squidgameThumbs.ts with base64 PNG thumbnails for each variant.
import { createCanvas } from "canvas";
import { drawSquidGameCell, SQUIDGAME_VARIANTS } from "./lib/squidgame";
import fs from "fs";
import path from "path";

const SIZE = 64;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_squidgame_thumbs.ts — do not edit by hand.",
  "export const SQUIDGAME_THUMBS: Record<string, string> = {",
];

for (const variant of SQUIDGAME_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  ctx.antialias = "subpixel";
  // Draw a level 3 cell (the most representative style)
  drawSquidGameCell(ctx as any, 0, 0, SIZE, 3, variant, 0);
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");

const outputPath = path.join(__dirname, "lib", "squidgameThumbs.ts");
fs.writeFileSync(outputPath, lines.join("\n"));
console.log(`Successfully generated thumbnails to ${outputPath}`);
